### ISSUE TITLE
Epic: e2e tests

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/otdfctl#248]
### Background

#234 recently added e2e test infrastructure to run a suite in CI with [bats](https://bats-core.readthedocs.io/en/stable/writing-tests.html) against a running platform instance.

There should be e2e tests that cover the majority of the CLI commands in `otdfctl`.

- [ ] namespaces CRUD
- [ ] attribute definitions CRUD
- [ ] attribute values CRUD
- [ ] subject-mappings CRUD
- [ ] resource-mappings CRUD
- [ ] kas-registry CRUD
- [ ] kas grants CRUD
- [ ] subject condition sets CRUD

**Comment by dmihalcik-virtru** [comment]
I've filed https://github.com/opentdf/otdfctl/issues/347 which should provide some of this functionality
